### PR TITLE
CBL-2888: 3rd party license list

### PR DESCRIPTION
**Pull request by LaurenNguyen14**

### CODE REVIEW

**Comment by LaurenNguyen14** [comment]
Generate 3rd party license list for CBL JAK 3.0.2

**Review by borrrden — APPROVED** [review]

**Review by bmeike — APPROVED** [review]
I'd have sworn we needed our license in there, not just the 3rd Party

**Review by bmeike — APPROVED** [review]
As discussed, I think we should have the license for our code, in there too.

**Comment by LaurenNguyen14** [comment]
> As discussed, I think we should have the license for our code, in there too.

Newest commit addresses conversation in slack that ce license should have: Apache license, 3rd party licenses

**Review by bmeike — APPROVED** [review]

**Pull request merged**
